In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
dataset=pd.read_csv("Dataset.csv")

In [23]:
dataset.head()

Day      Date  CodedDay  Zone  Weather  Temperature  Traffic
0  Wednesday  01-06-18         3     2       35           17        2
1  Wednesday  01-06-18         3     3       36           16        3
2  Wednesday  01-06-18         3     4       27           25        5
3  Wednesday  01-06-18         3     5       23           23        3
4  Wednesday  01-06-18         3     6       18           42        2

In [24]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder() 

In [25]:
dataset['Date']= le.fit_transform(dataset['Date'])

In [26]:
dataset.tail(10)

Day  Date  CodedDay  Zone  Weather  Temperature  Traffic
1429  Friday     9         5   135       18           25        4
1430  Friday     9         5   136       31            8        2
1431  Friday     9         5   137       13           11        4
1432  Friday     9         5   138       34           15        1
1433  Friday     9         5   139        5           43        4
1434  Friday     9         5   140       47           38        1
1435  Friday     9         5   141       15            8        4
1436  Friday     9         5   142       26           38        1
1437  Friday     9         5   143       16           34        3
1438  Friday     9         5   144       16           17        1

In [27]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1439 entries, 0 to 1438
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Day          1439 non-null   object
 1   Date         1439 non-null   int32 
 2   CodedDay     1439 non-null   int64 
 3   Zone         1439 non-null   int64 
 4   Weather      1439 non-null   int64 
 5   Temperature  1439 non-null   int64 
 6   Traffic      1439 non-null   int64 
dtypes: int32(1), int64(5), object(1)
memory usage: 73.2+ KB


In [28]:
X = dataset.iloc[:, 2:6].values
y = dataset.iloc[:, 6:7].values

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [40]:
print(X_test)

[[  3  36  27  45]
 [  3  55   1  25]
 [  4 106  13  29]
 ...
 [  3  17  43  30]
 [  5 109   6  25]
 [  1  53   9  37]]


In [30]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 300, random_state = 0)
regressor.fit(X_train,y_train)

C:\Users\girid\AppData\Local\Temp\ipykernel_8684\1592691624.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train,y_train)


RandomForestRegressor(n_estimators=300, random_state=0)

In [31]:
y_pred = regressor.predict(X_test)

In [32]:
if(y_pred.all()<2.5):
    y_pred=np.round(y_pred-0.5)
else:
    y_pred=np.round(y_pred+0.5)

In [33]:
df1=(y_pred-y_test)/y_test
df1=round(df1.mean()*100,2)
print("Error = ",df1,"%") 
a=100-df1
print("Accuracy= ",a,"%")

Error =  12.01 %
Accuracy=  87.99 %


In [34]:
y_pred = regressor.predict(X_test)
y_pred

array([3.35333333, 3.59      , 3.19666667, 3.37666667, 2.54666667,
       2.22666667, 3.08666667, 2.75666667, 3.51      , 2.28      ,
       3.16      , 2.73      , 2.85333333, 3.08333333, 3.47333333,
       2.14333333, 1.9       , 2.88666667, 3.34666667, 3.38666667,
       3.17333333, 2.74666667, 2.69      , 2.61      , 2.15666667,
       3.08      , 2.21666667, 3.02      , 2.7       , 3.38333333,
       2.19666667, 3.22333333, 3.1       , 2.53333333, 3.09333333,
       2.58      , 3.22      , 4.19      , 2.93666667, 3.14      ,
       2.50333333, 3.75333333, 2.77666667, 3.91      , 3.39      ,
       3.19333333, 2.41      , 2.96666667, 2.25666667, 3.36666667,
       3.85666667, 3.80666667, 3.82      , 3.07333333, 3.03666667,
       2.83666667, 2.96333333, 3.24333333, 2.56666667, 2.46      ,
       3.30333333, 3.07      , 3.24333333, 1.84333333, 2.88666667,
       3.34333333, 2.55666667, 3.7       , 2.86      , 2.77333333,
       2.97666667, 2.95      , 2.80666667, 2.93      , 2.97666

In [35]:
if(y_pred.all()<2.5):
    y_pred=np.round(y_pred-0.5)
    
else:
    y_pred=np.round(y_pred+0.5)

y_pred

array([3., 3., 3., 3., 2., 2., 3., 2., 3., 2., 3., 2., 2., 3., 3., 2., 1.,
       2., 3., 3., 3., 2., 2., 2., 2., 3., 2., 3., 2., 3., 2., 3., 3., 2.,
       3., 2., 3., 4., 2., 3., 2., 3., 2., 3., 3., 3., 2., 2., 2., 3., 3.,
       3., 3., 3., 3., 2., 2., 3., 2., 2., 3., 3., 3., 1., 2., 3., 2., 3.,
       2., 2., 2., 2., 2., 2., 2., 3., 3., 2., 1., 3., 2., 3., 3., 2., 3.,
       3., 2., 3., 3., 2., 2., 2., 2., 3., 2., 2., 2., 3., 3., 3., 2., 2.,
       2., 2., 3., 2., 3., 2., 3., 2., 2., 2., 2., 2., 3., 2., 2., 3., 3.,
       2., 2., 3., 2., 3., 3., 4., 3., 3., 4., 1., 2., 3., 3., 2., 3., 3.,
       3., 3., 3., 3., 3., 3., 2., 3., 3., 2., 3., 2., 2., 2., 2., 2., 3.,
       2., 3., 2., 3., 2., 3., 3., 2., 2., 3., 2., 2., 2., 2., 2., 2., 3.,
       2., 3., 2., 3., 3., 3., 2., 2., 2., 2., 2., 3., 2., 3., 2., 3., 3.,
       2., 2., 3., 2., 2., 3., 2., 2., 2., 2., 2., 2., 3., 2., 2., 3., 3.,
       3., 3., 2., 3., 3., 3., 3., 1., 3., 2., 3., 3., 3., 3., 2., 3., 3.,
       3., 2., 3., 3., 2.

In [36]:
df1=(y_pred-y_test)/y_test
df1=round(df1.mean()*100,2)
print("Error = ",df1,"%") 

Error =  12.01 %


In [37]:
a=100-df1
print("Accuracy= ",a,"%")

Accuracy=  87.99 %


In [38]:
print("Error = ",df1,"%")
print("Accuracy= ",a,"%")

Error =  12.01 %
Accuracy=  87.99 %


In [39]:
import pickle
model=open('model.pkl','wb')
pickle.dump(regressor,model)
model.close()